#!/system/bin/sh
# Boot into chroot environment

# Export chroot directory into variable
export NEW_ROOT=/data/local/kali

sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1

# Setup environment variables for shell environment
export HOME=/root
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/pwnix/bin
export TERM=xterm-color
export TZ=America/New_York
unset LD_PRELOAD

echo "[!] Welcome to the Pwn zone. Get your game face on."

/system/xbin/busybox stty columns 85
/system/xbin/busybox stty rows 46

# Drop user to shell
/system/xbin/busybox chroot $NEW_ROOT /bin/bash --login
