#!/system/bin/sh
# Initial chroot setup 

if [ ! -x /system/bin/getprop ]; then
  printf "Unable to execute /system/bin/getprop (needed for device detection)\n"
  exit 1
fi

if grep -q squashfs /proc/filesystems; then
  if [ ! -f /sdcard/Android/data/com.pwnieexpress.android.pxinstaller/files/stockchroot.sfs ]; then
    printf "Unable to read stockchroot.sfs.\n"
    exit 1
  else
    chroot_file="/sdcard/Android/data/com.pwnieexpress.android.pxinstaller/files/stockchroot.sfs"
  fi
else
  printf "No squashfs support present\n"
fi

# Error fast
set -e

# Unpack chroot
busybox mkdir -p /data/local/kali
busybox mkdir -p /data/local/kali-tmp
busybox mount -t auto "${chroot_file}" /data/local/kali-tmp
busybox cp -a /data/local/kali-tmp/* /data/local/kali
busybox umount /data/local/kali-tmp
busybox rm -r /data/local/kali-tmp

# Detect form factor
hardw=$(/system/bin/getprop ro.build.characteristics)
case ${hardw} in
  phone)
    PRODUCT="Pwn Phone"
    product="pwnphone"
    ;;
  tablet)
    PRODUCT="Pwn Pad"
    product="pwnpad"
    ;;
  *) exit 1 ;;
esac

# Set product based on form factor
echo "$PRODUCT" > /data/local/kali/etc/product
echo "$product" > /data/local/kali/etc/hostname
sed -i "s/127\.0\.0\.1.*/127.0.0.1      $product localhost/" /data/local/kali/etc/hosts
