#!/system/bin/sh
#Initial chroot v1 setup if it hasn't been done yet

#tests
if [ ! -r /data/local/kali_img/stockchroot.img ]; then
  printf "Unable to read /data/local/kali_img/stockchroot.img\n"
  exit 1
fi

if [ ! -x /system/xbin/busybox ]; then
  printf "Please install busybox (expected location is /system/xbin/busybox)\n"
  exit 1
fi

if [ ! -x /system/bin/getprop ]; then
  print "Unable to execute /system/bin/getprop (needed for device detection)\n"
  exit 1
fi

#immediately fail on error
#this may cause /data/local/kali to be partially populated if this script is run directly
set -e

#unpack chroot v1
busybox mkdir -p /data/local/kali
busybox mkdir -p /data/local/kali_img/kalitmp
busybox mount -t ext4 /data/local/kali_img/stockchroot.img /data/local/kali_img/kalitmp
cp -a /data/local/kali_img/kalitmp/* /data/local/kali
busybox umount /data/local/kali_img/kalitmp
busybox rm -r /data/local/kali_img/kalitmp

#detect product
hardw=$(/system/bin/getprop ro.hardware)
case ${hardw}
  hammerhead)
                PRODUCT="Pwn Phone 2014"
                product="pwnphone"
                ;;
  grouper)
  tilapia)
  deb)
  flo)
  tn8)
  shieldtablet)
                PRODUCT="Pwn Pad"
                product="pwnpad"
                ;;
  *) exit 1 ;;
esac

#set product
busybox echo "$PRODUCT" > /data/local/kali/etc/product
busybox echo "$product" > /data/local/kali/etc/hostname
busybox sed -i "s/127\.0\.0\.1.*/127.0.0.1       $product localhost/" /data/local/kali/etc/hosts

